exp_name: 'champ_stage2_no1_5'
output_dir: './exp_output'
seed: 42
resume_from_checkpoint: ''

stage1_ckpt_step: '56682'
stage1_ckpt_dir: '/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy_43187/champ/workspaces/wangzhen/code/champ-train-dev/exp_output/champ_stage1_addface_no1.5/saved_models'  # stage1 checkpoint folder

checkpointing_steps: 2000
save_model_epoch_interval: 10

data:
  train_bs: 1
  video_folder: '/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy_43187/champ/datasets/archived/Processed_Local_v3'  # Your data root folder
  guids: 
    - 'depth'
    - 'normal'
    - 'semantic_map'
    - 'DWpose'
  image_size: 768
  bbox_crop: true
  bbox_resize_ratio: [0.9, 1.5]
  aug_type: "Resize"
  data_parts:
    - "all"
  sample_frames: 24
  sample_rate: 4
  sample_margin: 30
  select_face: true
  face_folder: "/cpfs01/projects-HDD/cfff-6f3a36a0cd1e_HDD/zsy_43187/champ/workspaces/qingkun/champ_train/temp_with_face_mask"
  face_image_size: 256
  face_guids:
    - "lmk_images"

validation:
  validation_steps: 500
  aug_type: "Padding"
  clip_length: 12
  ref_images:
    - validation_data/ref_images/val-1.png
    - validation_data/ref_images/037.png
    - validation_data/ref_images/4.png
    - validation_data/ref_images/04.png
    - validation_data/ref_images/004.png
    # - validation_data/ref_images/02.png
    - validation_data/ref_images/002.png
    - validation_data/ref_images/0002.png
    - validation_data/ref_images/000001_all.png
    - validation_data/ref_images/000002_all.png
    - validation_data/ref_images/000003_all.png
  guidance_folders:
    - validation_data/guid_sequences/000_1
    - validation_data/guid_sequences/000_1
    - validation_data/guid_sequences/089_2
    - validation_data/guid_sequences/094_1
    - validation_data/guid_sequences/069_06
    # - validation_data/guid_sequences/009_1
    - validation_data/guid_sequences/027_0
    - validation_data/guid_sequences/085_07
    - validation_data/guid_sequences/01
    - validation_data/guid_sequences/02
    - validation_data/guid_sequences/03

  region_images:
    - validation_data/region_images/val-1.png
    - validation_data/region_images/037.png
    - validation_data/region_images/4.png
    - validation_data/region_images/04.png
    - validation_data/region_images/004.png
    # - validation_data/region_images/02.png
    - validation_data/region_images/002.png
    - validation_data/region_images/0002.png
    - validation_data/region_images/000001_all.png
    - validation_data/region_images/000002_all.png
    - validation_data/region_images/000003_all.png
                    
  guidance_indexes: [0, 30, 60, 90, 20, 0, 30, 60, 90, 20]            
solver:
  gradient_accumulation_steps: 1
  mixed_precision: 'fp16'
  enable_xformers_memory_efficient_attention: False 
  gradient_checkpointing: True 
  max_train_steps: 50000
  max_grad_norm: 1.0
  # lr
  learning_rate: 1e-5
  scale_lr: False 
  lr_warmup_steps: 1
  lr_scheduler: 'constant'

  # optimizer
  use_8bit_adam: True 
  adam_beta1: 0.9
  adam_beta2: 0.999
  adam_weight_decay:  1.0e-2
  adam_epsilon: 1.0e-8

noise_scheduler_kwargs:
  num_train_timesteps: 1000
  beta_start:          0.00085
  beta_end:            0.012
  beta_schedule:       "scaled_linear"
  steps_offset:        1
  clip_sample:         false

guidance_encoder_kwargs:
  guidance_embedding_channels: 320
  guidance_input_channels: 3
  block_out_channels: [16, 32, 96, 256]

unet_additional_kwargs:
  use_latent_attention: true
  num_hie_latent: 1
  use_inflated_groupnorm: true
  unet_use_cross_frame_attention: false 
  unet_use_temporal_attention: false
  use_motion_module: true
  motion_module_resolutions:
  - 1
  - 2
  - 4
  - 8
  motion_module_mid_block: true 
  motion_module_decoder_only: false
  motion_module_type: Vanilla
  motion_module_kwargs:
    num_attention_heads: 8
    num_transformer_block: 1
    attention_block_types:
    - Temporal_Self
    - Temporal_Self
    temporal_position_encoding: true
    temporal_position_encoding_max_len: 32
    temporal_attention_dim_div: 1

base_model_path: 'pretrained_models/stable-diffusion-v1-5'
vae_model_path: 'pretrained_models/sd-vae-ft-mse'
image_encoder_path: 'pretrained_models/image_encoder'
mm_path: './pretrained_models/mm_sd_v15_v2.ckpt'
ipadapter_path: "pretrained_models/ip-adapter-faceid-plusv2_sd15.bin"
image_encoder_ip_path: "pretrained_models/laion_clip"

weight_dtype: 'fp16'  # [fp16, fp32]
uncond_ratio: 0.1
noise_offset: 0.05
snr_gamma: 5.0
enable_zero_snr: True
